config:
  name: 开发环境

server:
  port: 13311

spring:
  web:
    resources:
      #      static-locations: "classpath:/dist"
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/ax_test33?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Abcd#1234
    driver-class-name: com.mysql.cj.jdbc.Driver
