config:
  name: 生产环境

server:
  port: ${AXINGER_CONFIG_SERVER_PORT:13312}

spring:
  datasource:
    url: ${AXINGER_CONFIG_DB_URL:jdbc:mysql://mysql8:3306/ax_test33?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${AXINGER_CONFIG_DB_USERNAME:root}
    password: ${AXINGER_CONFIG_DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
