config:
  name: 生产环境

server:
  port: 13312


spring:
  datasource:
    url: jdbc:mysql://mysql8:3306/ax_test33?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Abcd#1234
    driver-class-name: com.mysql.cj.jdbc.Driver
