server:
  port: 13301
  servlet:
    context-path: /axinger

spring:
  profiles:
    # 这个用来打包
    #    active: '@my-env@'
    #    active: dev
    active: ${SPRING_PROFILES_ACTIVE:dev}

logging:
  file:
    name: /var/log/a33-docker-jar
