version: '3.8'

services:
  app-1:
#    network_mode: "host"
    container_name: mall-payment-app
    build:
#      context: ./dir  # 指定包含 Dockerfile 的目录
      context: .
      dockerfile: Dockerfile  # 如果 Dockerfile 名字不是默认的 "Dockerfile"，则需要指定文件名
      tags: # 可以指定多个标签
#        - axinger/mall-payment-app:latest
        - axinger/mall-payment-app:1.0
    ports:
      - "9003:9003"
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - DEBUG=1
    networks:
      mynetwork:

networks:
  mynetwork:
    external: true
