version: '3.8'

services:
  app-1:
    build:
      context: .
      dockerfile: Dockerfile
      tags: # 可以指定多个标签
#        - axinger/mall-gateway-app:latest
        - axinger/mall-gateway-app:1.0
    container_name: mall-gateway-app
    ports:
      - "11000:11000" #不映射端口, 保护gateway, 让nginx反向代理gateway,但两者需要能连接成功
    volumes:
      - /etc/hosts:/etc/hosts
    environment:
      - DEBUG=1
    networks:
      mynetwork:

  app-2:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: mall-gateway-app-nginx
    ports:
      - "10000:80"
    volumes:
      - /etc/hosts:/etc/hosts
    networks:
      mynetwork:
networks:
  mynetwork:
    external: true
