spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: / #虚拟机
    username: admin
    password: admin
    #    publisher-confirms: true #消息发送到交换器确认
#    publisher-returns: true #消息发送到队列确认/**
